### ISSUE TITLE
Should the excel file questionnaire prefix contain the suffix ccs01?

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist-utilities#15]
The QV output has _ccs01 appended to the questionnaire column, but it doesn't append it in the TQ output. Both should be questionnaireprefix_ccs01.

So should the _ccs01 be included in the Excel and used as is, or will it be appended automatically to both outputs?

**Comment by ollylucl** [comment]
"So should the _ccs01 be included in the Excel and used as is, or will it be appended automatically to both outputs?"

You tell me! I can modify the code so _ccs01 gets appended automatically to both outputs, that's not difficult. If it's difficult/fiddly to modify whatever process generates the Excel file so that _ccs01 is in the questionnaire prefix column, we can just modify the code.

Would it be trivial to include the _ccs01 suffix in the relevant columns in the Excel file?

**Comment by HayleyMills** [comment]
Okay so it will be slightly easier for us if we didn't need to add the _ccs01 to the Excel, it's not onerous, but it might be easier for the studies to understand if it didn't include that. 

SO can we go with the script appending the _ccs01 please?

So in that case, I think it's only the TQ output which needs updating to append the _ccs01, as the QV already has this. 

It also means the filename of the output can just be the questionnaire prefix as is in the Excel file and the ccs01 won't need removing #14

**Comment by ollylucl** [comment]
I've pushed up a commit which adds _ccs01 to the values in the questionnaire prefix column in tq.txt
