### ISSUE TITLE
N/A's not removed from DV sheet

### ISSUE THREAD

**Issue by beckyoldroyd** [CLOSER-Cohorts/archivist-utilities#39]
Three rows in the DV sheet in the alspac_14_la22 mappings file 
[alspac_14_la22_mappings_wip_sm_bo.xlsx](https://github.com/user-attachments/files/16588932/alspac_14_la22_mappings_wip_sm_bo.xlsx) have N/A in them, but they weren't removed.

DV txt file output: 
[alspac_14_la22_dv.txt](https://github.com/user-attachments/files/16588959/alspac_14_la22_dv.txt)

**Comment by ollylucl** [comment]
The N/As aren't removed because the code checks for (and removes) rows containing 'NA' (i.e. without a forward slash).

It's trivial to modify the code so that it checks for N/As as well, but it does raise the issue about how we handle this sort of problem going forward. How about an extra text box on the user interface where users can specify what values they want to be removed? It can be populated by default with what the application currently removes ("NA", "Derived" and empty cells) and if you can add extra values (e.g. "N/A") if you want? @beckyoldroyd @HayleyMills

**Comment by HayleyMills** [comment]
Thanks @ollylucl I think that's probably overkill, we just need to be consistent in how we use the template, we're just getting used to it. If you think it's worth adding the N/A @beckyoldroyd sounds like it's a quick update for Olly.

**Comment by beckyoldroyd** [comment]
Thank you @ollylucl. I don't think there'll be enough different things that come up that we need to remove, outside of what's already on the list, to warrant adding a text box (although if we find that there is at some point in the future, that could be a good idea). If it's not too difficult to add N/A with the forward slash to the list for now, that would be great. Thanks again.

**Comment by ollylucl** [comment]
I've merged a commit into the main branch (https://github.com/CLOSER-Cohorts/archivist-utilities/pull/40) that addresses this issue. Try uploading a file with "N/A" values at https://closer-cohorts.github.io/archivist-utilities/, they should be removed. Remember to refresh the page https://closer-cohorts.github.io/archivist-utilities/, sometimes I have to F5 in order to get the most recent version of it. @HayleyMills @beckyoldroyd

**Comment by HayleyMills** [comment]
@beckyoldroyd  can you test this please? I've reassigned, @ollylucl please reassign if you're no longer working on an issue. Thanks.

**Comment by beckyoldroyd** [comment]
Thank you @ollylucl. I've tested it using the original Excel file and it has removed the first N/A but not the other two. The other two are lowercase ("n/a"), sorry I didn't spot this before, so please can you make an update so that it isn't case sensitive, or add n/a lowercase to the list of things to remove? Thanks again.

**Comment by beckyoldroyd** [comment]
@ollylucl tested with the original Excel file and working well. Thanks Olly.
